Citizen.CreateThread(function()

		-- lafa2k groove franklin
		RequestIpl("b2k_blimp_groove_v_franklins_milo_1")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_2")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_3")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_4")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_5")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_6")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_7")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_8")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_9")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_10")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_11")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_12")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_13")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_14")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_15")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_16")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_17")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_18")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_19")
		RequestIpl("b2k_blimp_groove_v_franklins_milo_20")
		
		-- lafa2k franklin
		
		RequestIpl("b2k_blimp_interior_v_franklins_milo_1")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_2")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_3")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_4")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_5")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_6")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_7")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_8")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_9")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_10")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_11")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_12")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_13")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_14")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_15")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_16")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_17")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_18")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_19")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_20")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_21")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_22")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_23")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_24")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_25")
		RequestIpl("b2k_blimp_interior_v_franklins_milo_26")
		
		-- lafa2k motel
		
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_1")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_2")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_3")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_4")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_5")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_6")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_7")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_8")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_9")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_10")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_11")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_12")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_13")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_14")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_15")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_16")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_17")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_18")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_19")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_20")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_21")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_22")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_23")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_24")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_25")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_26")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_27")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_28")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_29")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_30")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_31")
		RequestIpl("b2k_hw1_blimp_interior_v_motel_mp_milo_32")
		
end)